### ISSUE TITLE
Choice of std::size_t for subscripts?

### ISSUE THREAD

**Issue by stigrs** [kokkos/mdspan#105]
The C++ Core Guidelines recommends signed integers for subscripts (ES.107). Given the need for mdspan in scientific computing, it seems like a signed integer for subscripts would be more appropriate. Also for calling BLAS.

**Comment by mhoemmen** [comment]
If you'll take a look at the changelog in [the mdspan proposal P0009](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0009r14.html), LEWG asked us to change from signed integers to `size_t`, to make `mdspan` consistent with `span` and other Standard Library components.  This wasn't our idea, but we made the change before R11 (we're at R14 now) as requested by the working group.
