### ISSUE TITLE
Building with MSVC 2019 fails

### ISSUE THREAD

**Issue by stigrs** [kokkos/mdspan#107]
The commit "Fix building mdspan tests as CUDA code" (6930871) seems to break building with MSVC 2019:

D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(243,1): error C2121: '#': invalid character: possibly the result of a macro expansion 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(277,1): error C2121: '#': invalid character: possibly the result of a macro expansion 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(228,1): error C2760: syntax error: unexpected token 'identifier', expected ')' 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(385): message : see reference to class template instantiation 'std::experimental::extents<Extents...>' being compiled 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(228,1): error C2059: syntax error: ')' 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(228,1): error C2988: unrecognizable template declaration/definition 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(228,1): error C2143: syntax error: missing ';' before '&&' 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(228,1): error C2238: unexpected token(s) preceding ';' 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(228,1): error C2059: syntax error: '&&' 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(249,1): error C2334: unexpected token(s) preceding ':'; skipping apparent function body 
D:\a\1\s\build\_deps\mdspan-src\include\experimental\__p0009_bits\extents.hpp(385,1): fatal error C1903: unable to recover from previous error(s); stopping compilation 

Building with GCC and Clang works.

**Comment by mhoemmen** [comment]
May we ask what compiler flags you are using with MSVC 2019?  Also, what version of MSVC 2019 are you using?

**Comment by crtrott** [comment]
I can confirm that I see this too. We definitely need to set up more PR testing ...
I think MSVC doesn't like the ifdefing inside a macro. So I just need to replicate more stuff ...

**Comment by crtrott** [comment]
#111 Is the fix.
