### ISSUE TITLE
Avoid converting index to `size_type`

### ISSUE THREAD

**Issue by trivialfis** [kokkos/mdspan#109]
The call operator for both mdspan and layout policy mappings have template parameter `Index` for accepting index with types different than `size_t`.  Is it possible to remove the conversion that occurred in https://github.com/kokkos/mdspan/blob/183cab273ceb356091dee60b5c3f936e4850b7e5/include/experimental/__p0009_bits/mdspan.hpp#L245 ?

I'm happy to open a PR if such change is welcomed. ;-)

**Comment by dalg24** [comment]
> Is it possible to remove the conversion

Yes it looks like an oversight

> I'm happy to open a PR if such change is welcomed.

Please do

**Comment by trivialfis** [comment]
Thanks, will submit a PR.

**Comment by crtrott** [comment]
It is actually not quite clear-cut that it is a good idea to remove the explicit conversion. Say you index into something like this:
```c++
mdspan a(ptr, 4000, 1000, 1000);
a(3000, 1, 5);
```

without the conversion it might try to compute the offset using `int` and overflow. We are discussing what to do about this.

**Comment by crtrott** [comment]
Just to elaborate: currently mdspan just requires that the arguments to its access operator are convertible to size_type. Furthermore the requirements table for mapping says that the i... it takes is an index in the multi-dimensional index space. That means a custom mapping type may not need to support arbitrary types coming in. It would be valid to write a mapping which ONLY supports size_t being used to index into it, in which case its mdspan's responsibility to convert the indicies first.

**Comment by crtrott** [comment]
Note we are writing a change request against mdspan to address the size_t issue. Effectively we would add another template parameter to extents which sets the size_type which then is used by mapping and mdspan. However we can't default it, due to the variadic templates coming after it.

**Comment by mhoemmen** [comment]
The spec voted into the C++ draft [says](http://eel.is/c++draft/mdspan.mdspan.members) that `operator[]` has effects equivalent to `acc_.access(ptr_, map_(static_cast<index_type>(std::move(indices))...));`.

I was reviewing this issue with the intent to close it as "won't fix," when I noticed that `mdspan::operator()` is inconsistent with `mdspan::operator[]`.  `operator()` does _not_ cast the indices, while `operator[]` does.

* `operator()`: https://github.com/kokkos/mdspan/blob/d58ddaaa1869aa5ad8469c3b02abe025efab52a4/include/experimental/__p0009_bits/mdspan.hpp#L310

* `operator[]`: https://github.com/kokkos/mdspan/blob/d58ddaaa1869aa5ad8469c3b02abe025efab52a4/include/experimental/__p0009_bits/mdspan.hpp#L250

I will file a separate issue to fix this inconsistency.
