### ISSUE TITLE
standard_layout_static_array.hpp: warning C4100: '__tag': unreferenced formal parameter 

### ISSUE THREAD

**Issue by stigrs** [kokkos/mdspan#112]
An 'unreferenced formal parameter' warning is generated at lines 400 and 510 in standard_layout_static_array.hpp when compiling with MSVC 2019 and warning level 4 enabled. Seems like it can be fixed by changing 
`__construct_psa_from_dynamic_exts_array_tag_t<_IDynamic>  __tag ,`
to
 `__construct_psa_from_dynamic_exts_array_tag_t<_IDynamic> /* __tag */,`

**Comment by dalg24** [comment]
Thanks for reporting
