### ISSUE TITLE
Cannot assign mdspan

### ISSUE THREAD

**Issue by rscohn2** [kokkos/mdspan#119]
See https://godbolt.org/z/5EG6n5bfc

I cannot assign one view to another. There is a runtime assertion for:
```
m=view;
```
Is this an invalid use?

Here is the same program in case goldbolt link is no longer valid:

```
#include <https://raw.githubusercontent.com/kokkos/mdspan/single-header/mdspan.hpp>
#include <iostream>

namespace stdex = std::experimental;

template <class Span>
void show(Span span) {
    for (std::size_t i = 0; i < span.extent(0); ++i)
    for (std::size_t j = 0; j < span.extent(0); ++j)
      std::cout << "span(" << i << ", " << j << ") == " << span(i, j) << "\n";

}
int main() {
  std::array d{
    0, 5, 1,9,
    3, 8, 4,10,
    2, 7, 6,11,
    12, 13, 14, 15
  };

  stdex::mdspan m{d.data(), stdex::extents{4, 4}};
  std::cout << "Full\n";
  show(m);
  
  std::pair<size_t, size_t> pair(1,3);
  auto view = stdex::submdspan(m, pair, pair);
  std::cout << "Slice\n";
  show(view);
  std::cout << std::flush;

  m=view;

}
```

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Assigning layout_stride to layout_right with invalid strides.
Full
span(0, 0) == 0
span(0, 1) == 5
span(0, 2) == 1
span(0, 3) == 9
span(1, 0) == 3
span(1, 1) == 8
span(1, 2) == 4
span(1, 3) == 10
span(2, 0) == 2
span(2, 1) == 7
span(2, 2) == 6
span(2, 3) == 11
span(3, 0) == 12
span(3, 1) == 13
span(3, 2) == 14
span(3, 3) == 15
Slice
span(0, 0) == 8
span(0, 1) == 4
span(1, 0) == 7
span(1, 1) == 6
```

**Comment by mhoemmen** [comment]
I'm a bit surprised that this even compiles; it makes me wonder if the single-header implementation needs updating.

1. The `mdspan` `m` has compile-time extents that its constructor deduces from `stdex::extents{4, 4}`.  The extents are part of the type of `m`; assignment cannot change them.  The `mdspan` `view` has different extents, so it _should_ be a compilation error to assign `view` to `m`.
2. Even if `m` had run-time extents, `view` has extents (2,2) and strides (4,1).  It's not possible to express that layout with a `layout_left` `mdspan`.  Thus, the assignment is illegal (that would explain the run-time error you got).

**Comment by rscohn2** [comment]
Thanks for the explanation. I needed to store the result of submdspan, and I could not use auto. I was using:
```
stdex::mdspan<int, stdex::dextents<2>> x = submdspan(....
```
when I should have been using:
```
stdex::mdspan<int, stdex::dextents<2>, stdex::layout_stride> x = submdspan(....
```

**Comment by mhoemmen** [comment]
@rscohn2 Glad to be helpful! : - )  The specification (certainly as of R14) spells out precisely when you would expect to get `layout_stride` from `submdspan` with a `layout_left` or `layout_right` input.  It should be possible to write a type alias that deduces the returned layout type from the types of the inputs, without using `auto` or `decltype`.
