### ISSUE TITLE
Compilation with non-gnu compilers and `-pedantic`

### ISSUE THREAD

**Issue by chrisrichardson** [kokkos/mdspan#131]
When compiling with e.g. clang and `-pedantic` the following type of warnings are triggered:

```
mdspan.hpp:574:9: warning: token pasting of ',' and __VA_ARGS__ is a GNU extension [-Wgnu-zero-variadic-macro-arguments]
```
For some applications, we are using `-Werror -pedantic` which then causes this code to fail...

**Comment by crtrott** [comment]
see #132

**Comment by crtrott** [comment]
Was on vacation a while, closing this assuming your thumbsup meant that worked for you.
