### ISSUE TITLE
Returning address of local variable or temporary at line 346 in mdspan.hpp

### ISSUE THREAD

**Issue by stigrs** [kokkos/mdspan#145]
MSVC 2022 gives warning C4172: returning address of local variable or temporary at line 346 in mdspan.hpp.

**Comment by crtrott** [comment]
Do you know in which context? I can't immediately see how this would be a local variable or temporary, tracking it all back it just goes through a sequence a const & returning calls I believe.

**Comment by crtrott** [comment]
I don't see this warning in my MSVC 2022 build, can you provide more detailed reproducer?

**Comment by stigrs** [comment]
This could be a problem on my end. I tried to reproduce the warning, but was unable to. This issue can be closed. My apologies.
