### ISSUE TITLE
Internal compiler error with Intel 17?

### ISSUE THREAD

**Issue by RyanWollaeger** [kokkos/mdspan#16]
The following "bad pointer" error is obtained when attempting to compile mdspan with Intel 17.0.4:
```
experimental/__p0009_bits/basic_mdspan.hpp(124): internal error: bad pointer
    MDSPAN_TEMPLATE_REQUIRES(
    ^
```

Line 124 corresponds to the following code:
```
  MDSPAN_TEMPLATE_REQUIRES(
    class... IndexType,
    /* requires */ (
      _MDSPAN_FOLD_AND(_MDSPAN_TRAIT(is_convertible, IndexType, index_type) /* && ... */) &&
      (sizeof...(IndexType) == extents_type::rank_dynamic()) &&
      _MDSPAN_TRAIT(is_constructible, mapping_type, extents_type) &&
      _MDSPAN_TRAIT(is_default_constructible, accessor_type)
    )
  )
```

The compiler flags are:
```
C FLAGS: -w1 -vec-report0 -diag-disable remark -shared-intel -no-ftz -fma -diag-disable 11060 
     -xHost -qopenmp -g -O0 -inline-level=0 -ftrapuv -check=uninit -fp-model precise -fp-speculation 
     -debug inline-debug-info -fno-omit-frame-pointer -DDEBUG 
CXX FLAGS: -w1 -vec-report0 -diag-disable remark -shared-intel -no-ftz -fma -diag-disable 11060 
     -qopenmp -g -O0 -inline-level=0 -ftrapuv -check=uninit -fp-model precise -fp-speculation safe 
     inline-debug-info -fno-omit-frame-pointer -DDEBUG -early-template-check
```

Any information on a fix or workaround is much appreciated.

**Comment by crtrott** [comment]
We will look into this. Does it work with Intel 18/19?

**Comment by RyanWollaeger** [comment]
Thank you!  It worked with Intel 19.0.4 - we haven't tried with 18.

**Comment by crtrott** [comment]
Ok sounds good. Intel 17 will be on our support list. This thing is going to get moved into Kokkos proper at some point in the next few months, at which point we need to support all compilers which are on the official support list of Kokkos at that point. We will drop a number of compilers though, since we will also move to C++14 as the minimum. But Intel 17 is very likely still on our requirement list.

**Comment by dhollman** [comment]
I know at one point I had it working all the way back to Intel 15, but then I made some changes to get the Intel optimizer to realize that `std::array<ptrdiff_t, 3>` doesn't have a control flow dependence on itself (...yeah...), and in that process I think I probably regressed compatibility (we were also trying to get a paper out at that time, so you know how those things go).  I'll look at this; we're making some changes right now anyway to get ready to merge this into Kokkos later this year.

**Comment by dhollman** [comment]
Also, a lot of the things causing the most common compiler issues can be removed once we drop C++11 support.  I believe I regressed support for quite a few versions of various compilers when doing those workarounds also.

**Comment by KineticTheory** [comment]
As a follow up to the original report, LANL's intel/17.0.4 installation uses gcc/5.3.0's STL.  I don't think that critical, but it might be useful if you try to create a reproducer.
