### ISSUE TITLE
Can I construct a null mdspan with 0 dynamic ranks?

### ISSUE THREAD

**Issue by roastduck** [kokkos/mdspan#183]
Hi there. It seems that an `mdspan` should have a default constructor as described in the proposal, but I failed to construct such an `mdspan` as below:

```c++
mdspan<float, extents<13>> x;
```

The error is originated from the `requires` of `rank_dynamic() > 0` at https://github.com/kokkos/mdspan/blob/stable/include/experimental/__p0009_bits/mdspan.hpp#L128. I am wondering why is the constructor limited to non-zero dynamic ranks? Can I construct a null mdspan with 0 dynamic ranks?

**Comment by crtrott** [comment]
That is not an oversight, and it is defined as such in the proposal. The issue is that a default constructed mdspan with all compile time extents has in principle a non-empty set of valid access indices. However the pointer is nullptr, and thus an access would fail. This was discussed in the committee, and we preferred the stronger guarantees here for an mdspan being always legal to access by construction within its index space.

**Comment by dalg24** [comment]
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p0009r18.html
In `24.7.?.2 Constructors [mdspan.mdspan.ctor]`, the default constructor 1st constraint is "rank_dynamic() > 0 is true."

**Comment by crtrott** [comment]
Just to elaborate a bit more. With the current design it is always legal to loop over all extents and access the elements, assuming the mdspan was constructed legally. This follows from the preconditions of the constructors of mdspan, which require that the provided `data_handle` and `accessor` have an accessible range of the mappings `required_span_size`.

**Comment by crtrott** [comment]
One last thing. As documented here: https://github.com/kokkos/mdspan#c17 , the default constructor always exists in C++17 since I can't use a requires clause to disable it, and I can't SFINAE it away. One would have to go through too many hoops to make it happen (e.g. using base classes, or full out partial specialziation of mdspan).

**Comment by mhoemmen** [comment]
We have mdspan in the online C++ draft now! http://eel.is/c++draft/mdspan.syn

**Comment by roastduck** [comment]
I don't quite understand. Since the design is to "always legal to loop over all extents and access the elements" after constructed, why do we provide a default constructor for non-zero dynamic ranks? I think an `mdspan` constructed by a default constructor can never access its elements, no matter if there are dynamic ranks.

**Comment by crtrott** [comment]
Yeah but if you default construct an mdspan with dynamic ranks, the dynamic ranks have extent==0. And the legal range [0,0) is empty - i.e. there are no legal indices to be used.

**Comment by crtrott** [comment]
Btw. std::span has the same thing: no default constructor for `span<int, dynamic_extent>`

**Comment by roastduck** [comment]
Understood. But is there a best practice if I intend to create a null `mdspan`? Am I supposed to write `mdspan<float, extents<13>> x = nullptr`, or do I have to use `optional<mdspan>`?

Btw,

> Btw. std::span has the same thing: no default constructor for `span<int, dynamic_extent>`

do you mean "~no~ only default constructor for `span<int, dynamic_extent>`"?

**Comment by crtrott** [comment]
Ah yeah sorry its late :-)

And no `mdspan<float, extents<13>> x{nullptr}` is a violation of the preconditions of the constructor, so std::optional would be the standard compliant approach.

**Comment by roastduck** [comment]
Understood, so `mdspan` and `span` are designed like references (with mutable address) rather than pointers. But I think pointers are truly useful in some cases, comparing to `optional`s of references. Are there any plan for pointer-like `span`s?

`std::optional<mdspan>` is likely to introduce some overhead, because it needs at least an extra bit to record whether the `mdspan` is valid. On the contrary, a `nullptr` itself can indicate an invalid `mdspan`.

**Comment by crtrott** [comment]
You can always do `mdspan<int, extents<int,dynamic_extent>>`. In particular for 1D arrays where is practically no overhead other than the one extra int storage. Access of 1D mdspans like this does not involve the extent.

**Comment by roastduck** [comment]
Thanks. Feel free to close the issue.
