### ISSUE TITLE
mdspan::operator() is inconsistent with operator[]; both are inconsistent with the spec

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/mdspan#186]
Based on my comment here: https://github.com/kokkos/mdspan/issues/109#issuecomment-1235817012

The spec voted into the C++ draft [says](http://eel.is/c++draft/mdspan.mdspan.members) that `mdspan::operator[]` has effects equivalent to `acc_.access(ptr_, map_(static_cast<index_type>(std::move(indices))...));`.

There are two issues with the current mdspan implementation.  First, the backwards compatibility parentheses indexing operator `mdspan::operator()` is inconsistent with `mdspan::operator[]`.  `operator()` does _not_ cast the indices, while `operator[]` does.

* `operator()`: https://github.com/kokkos/mdspan/blob/d58ddaaa1869aa5ad8469c3b02abe025efab52a4/include/experimental/__p0009_bits/mdspan.hpp#L310
* `operator[]`: https://github.com/kokkos/mdspan/blob/d58ddaaa1869aa5ad8469c3b02abe025efab52a4/include/experimental/__p0009_bits/mdspan.hpp#L250

Second, neither of these two operators `std::move` the indices into the layout mapping's `operator()`.  This matters only for index types that are not integral and have nontrivial state.  (An example of a nonintegral index type would be a "tagged index type" that can be useful for avoiding confusion between different loop indices.  However, these are usually just wrappers around an integer.)  Nevertheless, it's not hard for us to fix this.

**Comment by crtrott** [comment]
Addressed in #214
