### ISSUE TITLE
Return type of `layout_stride::operator()` is incorrect

### ISSUE THREAD

**Issue by youyu3** [kokkos/mdspan#200]
Should return `index_type` but returns `size_t`
https://github.com/kokkos/mdspan/blob/stable/include/experimental/__p0009_bits/layout_stride.hpp#L426

**Comment by mhoemmen** [comment]
Confirmed, `layout_stride::mapping::operator()` should return `index_type` per the spec: http://eel.is/c++draft/views#mdspan.layout.stride.obs

**Comment by crtrott** [comment]
@youyu3 can you issue this against this repo too?

**Comment by youyu3** [comment]
@crtrott Sure I'll upstream my fixes to this repo when I get a chance.  Hopefully later this week.
