### ISSUE TITLE
is there any way to view multiple underlying data buffers into single mdspan?

### ISSUE THREAD

**Issue by zhuoqiang** [kokkos/mdspan#205]
Hi,

Maybe it is a abuse of mdspan but I wonder if it is possible to view multiple underlying data buffers with a same size through single mdspan object?

something like this:

``` cpp
// not working, just conceptual
auto d1 = vector{1, 2};
auto d2 = vector{3, 4};
auto d3 = vector{5, 6};

auto d = vector{d1.data(), d2.data(), d3.data()};
auto single_mdspan_view = mdspan{d.data(), 3, 2};
```

it seems to me that `mdspan` requires `ElementType*` as the underlying data parameter, so `d.data()` obviously not working here, not to metion the default layout policy.

But I am thinking if a customized layout / extents could make it work? for example:

- initialize mdspan with one of the buffer, like `d1.data()`
- store the distance between `d1.data()`, `d2.data()`, and `d2.data()`, `d3.data()` in the layout object so that it could compute memory location using indices and `d1.data()`

more generally, the indices could be seperated into 2 groups:

- those indices that used to find which buffer the location is mapping into
- and the rest indices to map the exact element in that particular buffer.

Not sure if it fits into the current mdspan concept, any suggeuests on this use case?

**Comment by bernhardmgruber** [comment]
In my understanding, this should totally work, since the data handle does not need to be `T*`. You will need to write your own accessor, since this type holds the data handle and determines how it is offset and accessed.

Here is a working example, but I am confident you can do better:
```c++
template <class ElementType, int Buffers>
struct multi_buffer_accessor {
  using offset_policy = multi_buffer_accessor;
  using element_type = ElementType;
  using reference = ElementType&;

  struct data_handle_type{
    size_t offset;
    std::array<std::span<ElementType>, Buffers> buffers;
  };

  constexpr multi_buffer_accessor() noexcept = default;

  constexpr data_handle_type offset(data_handle_type p, size_t i) const noexcept {
    // you may come up with a better implementation here
    p.offset += i;
    return p;
  }

  constexpr reference access(data_handle_type p, size_t i) const noexcept {
    // you may come up with a better implementation here
    i += p.offset;
    for (const auto& buffer : p.buffers) {
        if (i < buffer.size())
          return buffer[i];
        i -= buffer.size();
    }
    assert(false && "Out of bounds");
  }
};
```
https://godbolt.org/z/KqrMGsWbT

Since `offset` is harder to implement, I just postponed it to `access`, where I try to find which buffer span the index goes to. This is probably quite slow, so I leave it to you to come up with a better implementation!

Disclaimer: I am not affiliated with the Kokkos or mdspan team in any way.

**Comment by mhoemmen** [comment]
@bernhardmgruber Excellent example! : - D

There are a few different ways one could do this.  One possible issue with the `data_handle_type` design above is that it may be large and expensive to create and copy, especially if the number of buffers is large.  mdspan is nonowning, so it's perfectly legal for the accessor to have a pointer (just a normal raw pointer) to some storage struct.  I'm imagining a `multibuffer_array` analogous to mdarray (P1684), that has a storage struct in it.

**Comment by crtrott** [comment]
If you know how many buffers you have the above is good. I.e. its likely cheaper to make the data handle a bit larger, than going through pointer chasing for each access. My gutfeeling is that computing the correct buffer directly with modulo might be better than the loop. If you can have fixed size buffers underneath with power of 2 sizes you can even use shift and mask to compute the actual offset and which buffer to access into.

**Comment by crtrott** [comment]
This might be a good candidate for "How To"
