### ISSUE TITLE
How to fill or copy a mdspan?

### ISSUE THREAD

**Issue by rscohn2** [kokkos/mdspan#206]
I would like to use algorithms  std::fill and std::copy or their ranges equivalent on mdspan. These are algorithms where order of traversal does not matter. I don't see a begin(). Is there a recommended way to do it?

https://godbolt.org/z/5fEjbPn8d

**Comment by mhoemmen** [comment]
The simplest C++23 approach would be to use `cartesian_product` and `iota` to create a range expressing the domain (set of valid multidimensional indices) of an mdspan.

There are other ways to do it.  The following Compiler Explorer link shows some examples: https://godbolt.org/z/o59hdh8Kv

**Comment by rscohn2** [comment]
Thanks!
