### ISSUE TITLE
Optional 32-bit indexing for CUDA?

### ISSUE THREAD

**Issue by VasuAgrawal** [kokkos/mdspan#220]
I'm looking at switching some of my CUDA code over to use mdspan instead of hand-rolled accessors. One of the criteria I have, though, is that I'm able to perform most / all of the indexing and offset computations in 32-bit, rather than (usually) 64-bit that is `size_t`. This requirement is for register efficiency in CUDA cores, where the registers are 32-bit and not 64-bit. I read through [this paper](https://arxiv.org/pdf/2010.06474.pdf) about mdspan, and tried looking briefly through the [source code for extents](https://github.com/kokkos/mdspan/blob/stable/include/experimental/__p0009_bits/extents.hpp), but I didn't see any options to switch from `size_t` to e.g. `uint32_t` for extents and indexing. Is this something that is currently supported and I just haven't found it yet, or something that may be supported in the future, or something that's out of scope?

Thanks!

**Comment by mhoemmen** [comment]
@VasuAgrawal The first template parameter of `extents` is the index type.  You can use `int32_t` there for 32-bit extents.  The result of `.extents(r)` is `index_type`, which would be `int32_t` in this case.

```c++
constexpr int m = 4;
constexpr int n = 5;
std::vector<float> v(m * n);
std::mdspan m{v.data(), std::extents<int, m, n>{}};
static_assert(std::is_same_v<decltype(m.extent(0), int>);
```
