### ISSUE TITLE
Q: mdspan w/ dynamic rank <-> fully runtime mdspan definition

### ISSUE THREAD

**Issue by RalphSteinhagen** [kokkos/mdspan#245]
Maybe this is a silly question, but just needed some confirmation to avoid a fool's errand implementation attempt:

Most of the examples and from what I could gather from the lib implementation, most of the `std::mdspan` definitions assume a compile-time defined rank.  Is it possible to define `std::mdspan` with both rank and individual extends being defined dynamically?

The idea is to have a generic std::mdspan function return value where the rank and the individual extends are defined during runtime (only):
```cpp
std::mdspan<float> func(...) { /* ...*/ }
```

I saw `rank_dynamic()` and uses of `std::dynamic_extent` but no example or unit-tests regarding this ... thus my suspicion for that this isn't implemented/intended.

Our application is to store and access multiple named tensors that -- once defined during runtime -- share the same shape/data layout, e.g. with indexing like `[<data set>,  <1 dim | 2 dim | 3 dim | ... | N dim>]`.

Thanks in advance for any pointers ...

**Comment by mhoemmen** [comment]
@RalphSteinhagen wrote:
> Is it possible to define std::mdspan with both rank and individual extents being defined dynamically?

Yes.  In fact, the `dextents` alias exists specifically to make this easier.  Most uses of mdspan CTAD, such as the following, use dynamic extents.

```c++
vector<float> storage(num_rows * num_cols);
mdspan m{storage.data(), num_rows, num_cols);
```

> I saw `rank_dynamic()` and uses of `std::dynamic_extent` but no example or unit-tests regarding this....

Every time you see `dextents` or `extents<Something, dyn, dyn>` or the like in the [mdspan constructors test](https://github.com/kokkos/mdspan/blob/stable/tests/test_mdspan_ctors.cpp), we're exercising dynamic extents.

Here's an example from that file.  `dyn` here is an abbreviation for `stdex::dynamic_extent`.

```c++
TEST(TestMdspanListInitializationLayoutLeft, test_mdspan_list_initialization_layout_left) {
  std::array<int, 1> d{42};
  stdex::mdspan<int, stdex::extents<size_t,dyn, dyn>, stdex::layout_left> m{d.data(), 16, 32};
  ASSERT_EQ(m.data_handle(), d.data());
  ASSERT_EQ(m.rank(), 2);
  ASSERT_EQ(m.rank_dynamic(), 2);
  ASSERT_EQ(m.extent(0), 16);
  ASSERT_EQ(m.extent(1), 32);
  ASSERT_EQ(m.stride(0), 1);
  ASSERT_EQ(m.stride(1), 16);
  ASSERT_TRUE(m.is_exhaustive());
}
```

> Our application is to store and access multiple named tensors that -- once defined during runtime -- share the same shape/data layout....

mdspan has a constructor that accepts a layout mapping.  You may find this constructor useful for your application.  For example, you could create the layout mapping separately, then give it to each mdspan constructor.

```c++
// pointer to k-th tensor's data
extern float* my_data_handle(size_t k);

constexpr size_t rank = 3;
auto shape = dextents<size_t, 3>{5, 7, 11};
// Some compilers don't know how to do CTAD with nested classes,
// so you may need to spell out mapping's template argument.
layout_left::mapping mapping{shape};

using my_mdspan_type = mdspan<float, decltype(shape)>;
std::vector<my_mdspan_type> my_mdspans;
my_mdspans.reserve(num_mdspans);
for (size_t k = 0; k < num_mdspans; ++k) {
  my_mdspans.emplace_back(my_data_handle(k), mapping);
}
```

Please feel free to reopen this issue if you have any more questions; thanks!

**Comment by RalphSteinhagen** [comment]
@mhoemmen thanks for your quick reply. The above samples all seem to have a rank that is fixed at compile-time.

What I was looking for was something like:
```cpp
auto func(const std::vector<int>& data, const std::vector<std::size_t> dims) { // return fixed type regardless of rank/extents
    const std::size_t rank = dims.size();
    const std::size_t min_size = std::accumulate(dims.cbegin(), dims.cend(), 1, std::multiplies<double>());
    assert(data.size() >= min_size && "insufficient data size");

    //auto shape = stdex::dextents(dims); // <- requires static rank
    //stdex::layout_left::mapping mapping{shape};


    //return stdex::mdspan(data.data(), decltype(shape)); // <- doesn't work needs compile-time fixed type
    //return stdex::mdspan(data.data(), dims.data()); // <- ideally want something like this
    return stdex::mdspan(data.data());
}
```

Wrote a small compiler-explorer [example](https://godbolt.org/z/KeKWhnPGE) for illustration. Added a bit extra code for printing simple 2D matrices and type demangling (<-> easier to see whether types are the same or not and where they differ).

Is the non-templated function `func(...)` above possible? I heard conflicting statements... Thanks in advance.

**Comment by mhoemmen** [comment]
@RalphSteinhagen wrote:
> The above samples all seem to have a rank that is fixed at compile-time.

That is correct.  `extents::rank()` is a compile-time constant, so `mdspan::rank()` is a compile-time constant.  You can see that from [the definition of `mdspan::rank()`](http://eel.is/c++draft/mdspan.mdspan.overview).

`mdspan` requires that you know the rank at compile time.  There is no dynamic-rank `mdspan`.  This has always been the case, since the earliest version of the proposal circa 2014.

If you know the rank at compile time, you can use `span` to view an array of dimensions.

```c++
auto shape = stdex::dextents<int, 2>(span<int, 2>{dims.data()});
stdex::layout_left::mapping mapping{shape};
```

**Comment by RalphSteinhagen** [comment]
@mhoemmen thanks for confirming.

Unfortunately, we do not know the rank at compile time because it depends on the specific user input/query parameters. However, we have sort of a workaround for this limitation since the number of likely combinations is still finite.

While there are  -- I presume probably performance-related -- good reasons to define the rank at compile time, I hoped that we could re-use the same API similar to as the relationship between the compile-time `std::array<T, N>` is to the runtime `std::vector<T>` definition.

Any chance that this may be relaxed for future versions similar to, e.g.
```cpp
template<class T, std::size_t Extent = std::dynamic_extent> 
class span;
```
to include a fully dynamic rank, for example:
```cpp
template <class IndexType, size_t Rank = std::dynamic_extent>
using dextents = // ...
```

In any case, thanks a lot for your help, and I owe you another cup of :coffee: and/or :beers:!

**Comment by mhoemmen** [comment]
I'm glad to help! : - )  Here are some suggestions for work-arounds.

1. Kokkos has a `DynRankView` (dynamic-rank `View`; `Kokkos::View` behaves like an mdspan whose `data_handle_type` is `std::shared_ptr`): https://github.com/kokkos/kokkos/blob/master/containers/src/Kokkos_DynRankView.hpp

2. One could write an mdspan-like interface with an `std::variant<mdspan<T, dextents<size_t, std::make_index_sequence<MaxRank>(), Layout, Accessor>...>` inside.

@RalphSteinhagen wrote:
> While there are -- I presume probably performance-related -- good reasons to define the rank at compile time, I hoped that we could re-use the same API...

I could imagine a dynamic-rank class template with a _similar_ API.  It wouldn't quite be the same, because some member functions would cease to be `constexpr`.

If someone (perhaps you? : - ) ) were to write a WG21 proposal for this class template, it would almost certainly need to be a class with a different name.  Kokkos made the design choice to separate `View` from `DynRankView` for performance reasons.

**Comment by RalphSteinhagen** [comment]
Thanks for the pointers. Looking at DynRankView, I see that your world is 8-dimensional. :smirk: 

> I could imagine a dynamic-rank class template with a similar API.

Have been thinking about such an extension. Couldn't the member functions internally be guarded with constexpr-ifs on the `rank == std::dynamic_extent`? That should retain their constexpr-ness. This works for `std::span` and other use-cases for example like [this](https://compiler-explorer.com/z/x4aaPYG1d). 

But I agree, this would be a larger implementation change and probably several rounds within WG21 until C++35. I wonder why the dynamic case was not included (regardless of whether as mdspan and/or another type name) in the first place because in high ranks are quite common in algebra, MIMO, and other math systems. Maybe I am just naive ... :thinking: 

> If someone (perhaps you? : - ) ) were to write a WG21 proposal for this class template ...

If I would get a dollar/euro every time someone mentions this ... I would be able to fund my trip to Kona. 
Matthias Kretz is probably a much more knowledgeable, more gifted, and more thorough proposal writer than me.

**Comment by mhoemmen** [comment]
> I wonder why the dynamic case was not included (regardless of whether as mdspan and/or another type name) in the first place because in high ranks are quite common in algebra, MIMO, and other math systems.

Btw, "high rank" != "dynamic rank."  Nothing in the spec limits the rank other than `sizeof(size_t)`.

**Comment by RalphSteinhagen** [comment]
> Btw, "high rank" != "dynamic rank." Nothing in the spec limits the rank other than `sizeof(size_t)`.

Agree. Was referring to the DynRankView implementation and wondering why its dyn-concepts didn't make it into the standard ...
