### ISSUE TITLE
MacOS Include Order Issue

### ISSUE THREAD

**Issue by Twon** [kokkos/mdspan#28]
First of all thanks for the great implementation of mdspan!  This is currently used as a dependency in the official repository for the [wg21 proposal P1385 for Linear Algebra](https://github.com/BobSteagall/wg21) as based on feedback from the meeting mdspan was seen as the correct abstraction for matrix access.  

However, we are unfortunately experiencing some issue with our MacOS build as a result of mdspan relying on the `<version>` header.  The issue it seems is not the fault of mdspan, but the result of Apple-Clang shipping with 2 headers which define the same include guards. Both `<version>` and `<__cxx_version>` are declared with:

```
#ifndef _LIBCPP_VERSIONH
#define _LIBCPP_VERSIONH
...
#endif _LIBCPP_VERSIONH
```

The upshot of this if you include the wrong header before mdspan, then you accidentally pull in `<__cxx_version>` first, then when mdspan uses `<version>` its skips the contents of the file, causing mdspan to unnecessarily define _MDSPAN_NEEDS_TRAIT_VARIABLE_TEMPLATE_BACKPORTS, causing the build to then fail due to ambiguity around the being multiple definitions of `is_empty_v`.  Here is an example of the build error we see: https://travis-ci.org/github/BobSteagall/wg21/jobs/687745555.

A minimal reproduction case for the error can be produced as such:
# main.cpp
```
#include <iostream>  // <-- causes <__cxx_version> to be included before mdspan
#include <experimental/mdspan>

int main()
{

}
```

# CMakeLists.txt
```
cmake_minimum_required(VERSION 3.14)

project(mdspan_test)

include(FetchContent)
FetchContent_Declare(mdspan GIT_REPOSITORY https://github.com/kokkos/mdspan.git)
FetchContent_MakeAvailable(mdspan)

add_executable(mdspan_test main.cpp)
target_link_libraries(mdspan_test
    PRIVATE
        std::mdspan
)

set_target_properties(mdspan_test PROPERTIES
    CXX_STANDARD 20
    CXX_STANDARD_REQUIRED YES
    CXX_EXTENSIONS NO
)
```

Anyway, as mentioned this is really an issue with Apple-Clang, but I wanted to bring this to your attention because the unfortunate interaction means users of mdspan have to work around this by ensure mdspan is included first, which is somewhat brittle

**Comment by crtrott** [comment]
I think the issue was coming from something else (namely apple clang in C++17 or higher defining the typetraits but not the feature macro for the `is_**_v` stuff. With the PR I just opened #29 it works for me. Can you try that?

**Comment by Twon** [comment]
Hi, I've checked with the change you made and it's still failing, I've set up the example I outlined in a git repo here: https://github.com/Twon/mdspan_macos_include_order_issue.  If you follow the travis link in the read me you can see the build failures that are still occurring: https://travis-ci.org/github/Twon/mdspan_macos_include_order_issue.

Essentially you are right that the feature macro is not defined.  However, it is present and defined in the `<version>` header.  Except once you include any header that includes `<__cxx_version>` first then that causes `_LIBCPP_VERSIONH` to be defined, then once it includes `<version>` it will now skip the entire contents of the file due to include guard checks on the double defined symbol `_LIBCPP_VERSIONH`.  This then causes the feature macro not to be defined.

Given this is an error in libcxx shipping with Clang I'm not sure you can do much but detect when the error occurs and then warn users of the error.

**Comment by crtrott** [comment]
Hm that repo works for me. I cloned it, cd into it then mkdir build; cmake ../; make. That worked. Whats your cc --version?

**Comment by crtrott** [comment]
```
s1026909:Kokkos crtrott$ git clone git@github.com:twon/mdspan_macos_include_order_issue
Cloning into 'mdspan_macos_include_order_issue'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 17 (delta 4), reused 17 (delta 4), pack-reused 0
Receiving objects: 100% (17/17), done.
Resolving deltas: 100% (4/4), done.
s1026909:Kokkos crtrott$ cd mdspan_macos_include_order_issue/
s1026909:mdspan_macos_include_order_issue crtrott$ mkdir build
s1026909:mdspan_macos_include_order_issue crtrott$ cd build/
s1026909:build crtrott$ cmake ../
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected support for C++20 standard
-- Performing Test COMPILER_SUPPORTS_FCONCEPTS
-- Performing Test COMPILER_SUPPORTS_FCONCEPTS - Failed
-- Performing Test COMPILER_SUPPORTS_FCONCEPTS_TS
-- Performing Test COMPILER_SUPPORTS_FCONCEPTS_TS - Failed
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/crtrott/Kokkos/mdspan_macos_include_order_issue/build
s1026909:build crtrott$ make
Scanning dependencies of target mdspan_test
[ 50%] Building CXX object CMakeFiles/mdspan_test.dir/main.cpp.o
[100%] Linking CXX executable mdspan_test
[100%] Built target mdspan_test
s1026909:build crtrott$ 
```

**Comment by crtrott** [comment]
Also clicking on your travis link it shows passing tests?

**Comment by Twon** [comment]
Hi, thanks for taking a look at this!  Yes, this now worked for me.  I should have said I set up a repo here for this: https://github.com/Twon/mdspan_macos_include_order_issue.  As you can see the build is now passing for Xcode 10 & 11 where it was previously failing: https://travis-ci.org/Twon/mdspan_macos_include_order_issue.

Many thanks for addressing this so quickly!

**Comment by Twon** [comment]
> Also clicking on your travis link it shows passing tests?

Yes, but only because we have put a workaround in here: https://github.com/BobSteagall/wg21/blob/master/include/linear_algebra.hpp#L24.  I've created a pull request that builds against these changes and removed the workaround, and it looks like this resolves the issue: https://github.com/BobSteagall/wg21/pull/51

**Comment by crtrott** [comment]
Ah yeah I meant the travis thing in your testcode, I think you posted here, and then later deleted the post - but I had already gotten the email ;-).

**Comment by Twon** [comment]
Yes, I did, then realised I had tested without setting the branch containing your changes, doh!  I checked it again, this time against your changes and the issue has been resolved.  So I agree, the changes in the PR do fix the issue.  Thanks for looking at this so quickly, much appreciated.

**Comment by crtrott** [comment]
Great!

**Comment by Twon** [comment]
Closing the issue now its resolved.  I've renabled the LA repo from building at head of master and all tests are passing on CI: https://github.com/BobSteagall/wg21/pull/52
