### ISSUE TITLE
Cannot build with exceptions disabled

### ISSUE THREAD

**Issue by burnpanck** [kokkos/mdspan#316]
There is a single `throw` in the source in `layout_right.hpp`: https://github.com/kokkos/mdspan/blob/0e6a69dfe045acbb623003588a4aff844ea4b276/include/experimental/__p0009_bits/layout_right.hpp#L164-L167

This prevents the library from compiling with `-fno-exceptions`, typical for embedded environments. The comment states that this indeed causes a terminate anyway, it would probably be better to use  `std::terminate` or `std::abort` directly.

Interestingly, the matching `throw` within `layout_left.hpp` must have been refactored to that end some time between `v0.6.0` and `stable`:
https://github.com/kokkos/mdspan/blob/879869d6740c47d40c02754cc05e241c1c66520f/include/experimental/__p0009_bits/layout_left.hpp#L164-L165

So this looks like an unfinished refactor to me.

**Comment by groutoutlook** [comment]
Hi, I think I have seen a lot of `throw` in the code again... and I have to use `-fno-exception` and `-fno-rtti`. Can we make some flags (to the codegen script) so people like me can opt-out of exception?

**Comment by mhoemmen** [comment]
@groutoutlook Would you consider opening a new issue with your specific requirements?  Thanks!

**Comment by groutoutlook** [comment]
Yeah I will, although recently I just finished my work without mdspan so my incentive to make a new issue is low. Will take a while for me to do that.
