### ISSUE TITLE
BSD license for inclusion in SciPy?

### ISSUE THREAD

**Issue by izaid** [kokkos/mdspan#321]
Hello all! Thanks for making such a great reference implementation of `std::mdspan` available.

Over at SciPy, we've been considering using exactly this implementation to help us with some C++ <> NumPy interoperability for special function computations [1].  However, there appears to be an issue in that SciPy is distributed under the BSD license, and specifically finds Apache licenses incompatible. The details are at http://scipy.github.io/devdocs/dev/core-dev/index.html#licensing

Is there any chance kokkos/mdspan would be willing to grant us something under the BSD license? Or if anyone has any thoughts on another way we can include this `std::mdspan` reference implementation in a way that is compatible with SciPy's policy?

Many thanks!

[1] You can see the issue at https://github.com/scipy/scipy/pull/20320, but a lot of the details are not relevant here.

**Comment by crtrott** [comment]
Note that we are under Apache-2 with LLVM Exceptions. Thus no attribution is required in binary code, and you just need to not delete our license notice in headers you copy.

**Comment by lucascolley** [comment]
this can probably be closed now - `mdspan.hpp` was included in SciPy following discussion in scipy/scipy#20396
