### ISSUE TITLE
Missing restriction on ElementType and AccessorPolicy​::​element_type being the same

### ISSUE THREAD

**Issue by pauleonix** [kokkos/mdspan#330]
According to [the standard draft](https://eel.is/c++draft/views#mdspan.mdspan.overview-2.3), [cppreference](https://en.cppreference.com/w/cpp/container/mdspan) and common sense these need to be the same, but at least when using the single header version I can instantiate e.g. `std::mdspan<float, std::dextents<int, 2>, std::layout_right, std::default_accessor<double>>` or `std::mdspan<float const, std::dextents<int, 2>, std::layout_right, std::default_accessor<float>>` without a compiler error.

See https://godbolt.org/z/nx4YE91G3

**Comment by mhoemmen** [comment]
Thank you for reporting this!  I agree that this is a bug.  The two types need to be the same.  mdspan's Mandates clause ([mdspan.mdspan.overview] 2.3) includes "`is_same_v<ElementType, typename AccessorPolicy​::​element_type>` is `true`."  "Mandates" means "should be ill-formed if violated, e.g., by using a `static_assert`."

Would you consider submitting a PR with a fix?
