### ISSUE TITLE
Conan support

### ISSUE THREAD

**Issue by mpusz** [kokkos/mdspan#42]
Hi, it would be great to have your library in Conan to simplify its usage by a wider audience. I can help you with that. But first, it would be great to have some official release (0.1.0?) done as it seems that the library is still on 0.0.1 with no release up to now.

**Comment by dalg24** [comment]
[Done](https://github.com/kokkos/mdspan/releases/tag/mdspan-0.1.0)

**Comment by mpusz** [comment]
Please see PR https://github.com/conan-io/conan-center-index/pull/5382 and let me know if everything looks OK to you. If yes, I will submit this PR for review.

_Note:_ Typically releases are just numbers without `mdspan-` prefix as it results in `mdspan-mdspan-*` archive (https://github.com/conan-io/conan-center-index/pull/5382/files#diff-66c79223ea605a0847efe27e41eefae3fb8d0e148c97510248b1350b86b385d8R20).

**Comment by dalg24** [comment]
> Typically releases are just numbers without mdspan- prefix as it results in mdspan-mdspan-* archive 

I was following [boost](https://github.com/boostorg/boost/releases) convention but I don't mind changing.

In the meantime I realized I forgot to update https://github.com/kokkos/mdspan/blob/9d1acac543053cbe6839273f550b1ece218e9696/CMakeLists.txt#L4

**Comment by mpusz** [comment]
You can still update it. The Conan recipe is not done.

The current issue I see is that the library claims to be C++11 compatible but there are a few `std::integer_sequence` being used and a few other issues. See: https://github.com/conan-io/conan-center-index/pull/5382#issuecomment-830289540

**Comment by mpusz** [comment]
A full error log can be found here: https://c3i.jfrog.io/c3i/misc/logs/pr/5382/4/mdspan/0.1.0//5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9-test.txt.

**Comment by dalg24** [comment]
This is weird.  I am not sure what is wrong.  I wasn't able to reproduce on my local build.
https://github.com/kokkos/mdspan/blob/9d1acac543053cbe6839273f550b1ece218e9696/include/experimental/__p0009_bits/trait_backports.hpp#L87-L130

I will get back to it later.  Unless you want to take a stab at it?  ;)

**Comment by crtrott** [comment]
I think we are dropping C++11 because our main users internally went to C++14 as a minimum and it simplifies our life a bit. I presume its not a big issue for you?

**Comment by mpusz** [comment]
No, I may easily set C++14 as a minimum requirement. I just didn't want to overconstrain the Conan package if it was not necessary.

**Comment by mpusz** [comment]
OK, with C++14 set as a minimum requirement the Conan package is green: https://github.com/conan-io/conan-center-index/pull/5382#issuecomment-830792728. Should I submit this PR for review or maybe you want to do some last-minute changes (fix CMake version, change the labeling scheme, ...)?

**Comment by mpusz** [comment]
Could you please confirm that no changes are expected and that I can submit the PR to ConanCenterIndex as is? If you want to do some changes please feel free to let me know as well.

**Comment by mpusz** [comment]
Done: https://conan.io/center/mdspan.
