### ISSUE TITLE
Implement basic_mdspan::span()

### ISSUE THREAD

**Issue by keryell** [kokkos/mdspan#45]
I wanted to use this member function in a project, but, too bad, this not yet implemented...
https://github.com/kokkos/mdspan/blob/stable/include/experimental/__p0009_bits/basic_mdspan.hpp#L302
```c++
  // [mdspan.basic.codomain], basic_mdspan observers of the codomain
  // TODO span (or just `codomain` function, as discussed)
  // constexpr span<element_type> span() const noexcept;
```

**Comment by crtrott** [comment]
We actually removed it in a recent version of the proposal.

**Comment by keryell** [comment]
Ah, too bad.
It is still in *22.7.�.1 basic_mdspan overview [mdspan.basic.overview]* of http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0009r10.html which was for me the latest published version.
So, where is the latest provisional proposal?

**Comment by keryell** [comment]
OK, https://github.com/ORNL/cpp-proposals-pub/pull/137 just landed as P0009r11.
Now I need an implementation of `submdspan()`. :-) But this is not an issue for https://github.com/triSYCL/triSYCL/pull/304 to use the old naming for now.
