### ISSUE TITLE
`submdspan` conventions

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/mdspan#62]
Is there a reason to use `[begin, end[` when taking a `submdspan` with pairs ? It is a different convention from `subspan` in `std::span` that uses the pair `(offset, count)`.

I also noticed that it is a free function whereas in `std::span` it is a member function.

Thomas P.

**Comment by mhoemmen** [comment]
1. Inclusive begin, exclusive end has precedence in other languages, such as Python.  It's the C-style indexing version of what Fortran does.
2. `span` came from an early version of `mdspan`, so it might be more apt to ask this question of `span` ; - ) .
2. P0009 went through a _lot_ of review (it's on R12++ now).

**Comment by tpadioleau** [comment]
Thank you for explaining the rationale behind the choices.
