### ISSUE TITLE
Submdspan issue

### ISSUE THREAD

**Issue by tpadioleau** [kokkos/mdspan#63]
I am trying the `submdspan` function and I have unexpected results. Here is my test

```cpp
#include <array>
#include <cstdint>
#include <experimental/mdspan>
#include <iostream>

using namespace std::experimental;

template <class ET, class EP, class LP, class AP>
void print_layout(mdspan<ET, EP, LP, AP> const &t) {
  if constexpr (std::is_same_v<LP, layout_left>) {
    std::cout << "layout=left";
  } else if constexpr (std::is_same_v<LP, layout_right>) {
    std::cout << "layout=right";
  } else if constexpr (std::is_same_v<LP, layout_stride>) {
    std::cout << "layout=stride";
  }
}

int main(int argc, char **argv) {
  std::array<double, 100> raw{};
  mdspan<double, dextents<2>, layout_right> s(raw.data(), 10, 10);

  std::cout << "Expected: layout=right, strides=[10,1], extents=[10,10]\n";
  std::cout << "Result: ";
  print_layout(s);
  std::cout << ", strides=[" << s.stride(0) << "," << s.stride(1) << "]";
  std::cout << ", extents=[" << s.extent(0) << "," << s.extent(1) << "]" << std::endl;
  std::cout << std::endl;

  auto s1 = submdspan(s, full_extent, std::pair(3ul, 7ul));
  std::cout << "Expected: layout=stride, strides=[10,1], extents=[10,4]\n";
  std::cout << "Result: ";
  print_layout(s1);
  std::cout << ", strides=[" << s1.stride(0) << "," << s1.stride(1) << "]";
  std::cout << ", extents=[" << s1.extent(0) << "," << s1.extent(1) << "]" << std::endl;

  std::cout << std::endl;
  auto s2 = submdspan(s, std::pair(3ul, 7ul), full_extent);
  std::cout << "Expected: layout=right, strides=[10,1], extents=[4,10]\n";
  std::cout << "Result: ";
  print_layout(s2);
  std::cout << ", strides=[" << s2.stride(0) << "," << s2.stride(1) << "]";
  std::cout << ", extents=[" << s2.extent(0) << "," << s2.extent(1) << "]" << std::endl;

  return 0;
}
```

The output is the following where I print my expectation and the result:

```
Expected: layout=right, strides=[10,1], extents=[10,10]
Result: layout=right, strides=[10,1], extents=[10,10]

Expected: layout=stride, strides=[10,1], extents=[10,4]
Result: layout=right, strides=[4,1], extents=[10,4]

Expected: layout=right, strides=[10,1], extents=[4,10]
Result: layout=stride, strides=[10,1], extents=[4,10]
```

Am I missing something ?

**Comment by mhoemmen** [comment]
The [`mdspan` proposal](https://wg21.link/P0009) does not specify the layout of the `mdspan` returned by `submdspan`.  It just specifies the behavior of the returned `mdspan`.  If I recall correctly, the intent was to allow implementation freedom.

In your second case, `submdspan` asks to view all the rows with `full_extent`, and a contiguous subset of columns.  This makes `layout_right` with stride 4 another correct way to describe the result.

In your third case, either `layout_right` or `layout_stride` would be correct layouts.  From what I can tell from [the code here](https://github.com/kokkos/mdspan/blob/5694f21c39f3b948d06a0c63b9c219bf802e28a8/include/experimental/__p0009_bits/submdspan.hpp#L114), the implementation doesn't optimize this special case.  Nevertheless, the returned `mdspan`'s layout is still correct, even though `layout_stride` is more general than needed.

**Comment by tpadioleau** [comment]
> The [`mdspan` proposal](https://wg21.link/P0009) does not specify the layout of the `mdspan` returned by `submdspan`. It just specifies the behavior of the returned `mdspan`. If I recall correctly, the intent was to allow implementation freedom.

I understand your point, one cannot rely on the return type of `submdspan`.

> In your second case, `submdspan` asks to view all the rows with `full_extent`, and a contiguous subset of columns. This makes `layout_right` with stride 4 another correct way to describe the result.

In this case I don't think the layout can be `layout_right` which is contiguous by definition whereas the slice cannot be. The two mdspan `s` and `s1` don't seem to refer to the same elements in the codomain:
```cpp
  for (std::size_t i = 0; i < s1.extent(0); ++i) {
    for (std::size_t j = 0; j < s1.extent(1); ++j) {
      std::cout << (&s1(i, j) == &s(i, 3 + j)) << " ";
    }
    std::cout << std::endl;
  }
```
This returns `true` only for the first row. That is why I was expecting a stride of 10 for `s1.stride( 0 )`.

If I am not mistaken the return value of `submdspan` does not satisfy the following point

> If src.is_strided() is true, then sub.is_strided() is true, and for all k in the range [0, src.rank()), if map_rank[k] != -1 is true, then sub.stride(map_rank[k]) equals src.stride(k).

**Comment by mhoemmen** [comment]
Hm, I think you're right -- that does look like a bug.  Thanks for pointing this out!
