### ISSUE TITLE
Internal compiler error with nvcc + gcc

### ISSUE THREAD

**Issue by michael-afanasiev** [kokkos/mdspan#65]
Hi everyone,

I'm getting a compilation error with `nvcc` when using `gcc` as a host compiler. Using `clang` as a host compiler works, as does a CPU-only compilation. Godbolt link: https://godbolt.org/z/zrhP5zY9W.

Is this a bug, or am I misusing something here?

Thanks alot for your mdspan efforts! Really liking it so far.

**Comment by michael-afanasiev** [comment]
Quick note: looks to be due to the use of `[[no_unique_address]]` -- turning of its use in mdspan allows the compilation to complete: https://godbolt.org/z/6hEYeqhGn.

**Comment by mhoemmen** [comment]
@michael-afanasiev Thanks for diagnosing this issue!  "Internal Compiler Error" generally indicates a compiler bug.  Are you able to use the library without the `[[no_unique_address]]` feature for now?

**Comment by michael-afanasiev** [comment]
@mhoemmen Yes, not a huge deal -- the nvcc + gcc builds can just turn it off. Not sure how much interaction you have with the nvcc team, but if it helps i could close this in favor of a report over on the nvidia forums.

**Comment by mhoemmen** [comment]
@michael-afanasiev Please do submit this as an nvcc bug -- it helps to have more independent confirmation.  Thanks!

**Comment by michael-afanasiev** [comment]
@mhoemmen -- sorry, let this slip for a bit. nvcc issue filled [here](https://forums.developer.nvidia.com/t/issue-with-nvcc-gcc-and-no-unique-address/191507?u=michael.afanasiev).

**Comment by mhoemmen** [comment]
@michael-afanasiev Thanks for filing the ticket! : - )

**Comment by crtrott** [comment]
I think this is fixed.
