### ISSUE TITLE
Backport of no_unique_address

### ISSUE THREAD

**Issue by dhollman** [kokkos/mdspan#7]
Right now, on non-C++20 compilers, `mdspan` and other parts of the implementation are space inefficient because the `[[no_unique_address]]` (written as `_MDSPAN_NO_UNIQUE_ADDRESS`) does nothing.  We need to find a way to backport to the EBO version of `no_unique_address` without introducing overhead on the newer compilers (and without going crazy with bifurcating the implementation using `#ifdef`s).

**Comment by nliber** [comment]
Both libc++ and libstdc++ implement EBO for empty types in a tuple.  One way to accomplish this is to use tuple and write private const and non-const getters to return references to the various members.

Just a thought...

**Comment by dhollman** [comment]
Unfortunately, not all of the things we would want to use `mdspan` for have reliable support for `tuple` (e.g., Cuda, HIP).  It's not much harder to just manually do this, but I just have to get around to doing it.  Also, we need to make sure that this happens without increasing the cost to the inliner in the case of the modern attribute (even if we force inline, we have to be sure the extra layer of abstraction isn't adding to the compilers internal inlining limits for functions that use it).

**Comment by dhollman** [comment]
Also, this strategy doesn't work transitively, since some of the uses of `_MDSPAN_NO_UNIQUE_ADDRESS` are on the only data member of the class template.

`[[no_unique_address]]` is quietly one of my favorite C++20 features, though maybe that's a sign I do way too much generic programming.

**Comment by crtrott** [comment]
@dhollman yes and yes. 
(it is a sign you do too much generic programming, but I also like this feature ;-) )

**Comment by dhollman** [comment]
Done and merged (#19). There is still a bug with some things not being recognized as empty by some implementations, but I'll open a separate issue for this.
